sudo: false
addons:
  apt:
    packages:
    - pandoc
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - git clone https://github.com/tufu9441/maupassant-hexo.git themes/maupassant
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public