# Header
menu:
  ## If your site is put in a subdirectory, set Home as '/child/'
  Home: /
  Archives: archives
  About: https://waynehfut.com

social:
  email: waynehfut@gmail.com
  twitter: waynehfut
  weibo: waynehfut
  github: waynehfut
  # googleplus:
  rss: /atom.xml

# Content
fancybox: true # set to true if you want to use it
infinite_scroll: false # set to true if you want to use it
toc_words: "Outline" # the line shown in toc
show_toc_by_default: true # to show toc if `toc:` is not specified in post

duoshuo: #duoshuo_shortname
disqus: dandiaoboke #disqus _shortname
google_analytics: UA-116559759-1 #Google Analytics Tracking Code
google_adsense_page_level_ads: #Google Adsense Page Level Ads Code

less:
  paths:
    - source/css
  compress:
    true
